### ISSUE TITLE
PNB Store

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#1]
I created a new store for PNB, Peshtigo National Bank.  I walked through entering multiple sizes that the jacket comes in.  However, when I go to order the jacket as if I’m a buyer, I click the size drop down and only the first size I created is there. I can’t choose a different size. ?? 

Also when I click ADD & CONTINUE SHOPPING nothing happens.  When I click ADD TO CART it appears as though nothing happens bc the screen stays exactly the same, but then I looked at the cart icon and saw a 1 in there so it was added.  But then I wondered what to do next. Continue Shopping isn’t working so either I click Back or on the cart.  

When I click on my cart and then Checkout, it asks for my name and address.  Will we have a separate Bill To verses Ship To or must they be the same?

On the “home page” for the PNB store, the description I entered runs from the very beginning of the screen to the very end of the screen.  Is there a way to shorten up that box a little so it looks nicer and not like it’s running off the page?

Also on the “home page” for the PNB store, is it possibly for the product image to show up there rather than a generic cart image?  Otherwise the user will have to click on every single product to be able to view it?

**Comment by smitdalt** [comment]
I fixed everything in this issue except for the ability to add multiple sizes and colors at one time. You might need to delete browser cache after I make updates to see them (Shift+f5 on chrome)

**Comment by smitdalt** [comment]
Moving "When I click on my cart and then Checkout, it asks for my name and address. Will we have a separate Bill To verses Ship To or must they be the same?" to Checkout Process issue, Everything else in this issue fixed.
