### ISSUE TITLE
Product Image Size?

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#10]
Are there image size restrictions we need to stay within?  I added a hoodie and a ladies polo in the PNB store and both extend past the text that is the product name.  It is still readable on the hoodie because the hoodie is a light color and the text is black.  But the ladies polo is navy so the black text is hard to read.  I suspect if we upload smaller product images this would solve this issue?

**Comment by smitdalt** [comment]
I added styles to force images to fit within the box without overlapping product name text.
