### ISSUE TITLE
Cart Qty

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#11]
As a shopper (not admin), I put 1 navy ladies SM polo in my cart and the cart icon changed to (1).  Then I put a qty of 2 grey ladies 2XL polos in my cart and the cart icon changed to (2).  So I suspect it will only count how many unique items are in my cart, but will not count if I have more than 1 of an item in my cart?

**Comment by smitdalt** [comment]
Yes, this only counts unique items in the cart. I could change it to be the total quantity if that makes more sense

**Comment by karentooley** [comment]
I feel like as a buyer, it makes more sense to count total qty.  So if that is an easy change, yes, please change to total qty.  TY!

**Comment by smitdalt** [comment]
Cart now shows total item quantities instead of unique items.
