### ISSUE TITLE
Checking in?

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#16]
Just checking in to see where this is at.  Peshtigo Bank would like Blue Fuel to create a store from them but would like to wait for this new store so they can opt to not use credit card payments.  They have a annual meeting this Friday, 2/12 and would like to update everywhere on where they are at with an online store.  Do you think it they tell everyone the store is aimed to be ready by April that that would be feasible?  And if its earlier, than awesome but if not this still gives us 2 months?  Please let me know your thoughts.  TY

**Comment by smitdalt** [comment]
April is doable for sure. Adding an option to opt out of online credit card payments per store shouldn't add too much complexity to either the front- or back-end.

**Comment by nwenthold** [comment]
Do you have an update on where the store currently stands? NPAA wants last year's store reopened next Friday and we were hoping to be able to use the new format--is 2/26 feasible?
