### ISSUE TITLE
Status update?

### ISSUE THREAD

**Issue by nwenthold** [smitdalt/BFStoreIssues#17]
Do you have an update on where the store currently stands? NPAA has requested that we reopen last year's store starting next Friday and we are hoping to be able to use the new format--is going live before 2/26 feasible?

**Comment by smitdalt** [comment]
I have a break from school for the next week and can work on the store quite a bit. If I let you know by 02/24 is that enough time?

**Comment by nwenthold** [comment]
That should be okay. Thanks!

**Comment by smitdalt** [comment]
I have everything working properly to run a basic store, but haven't been able to set up SSL by today. I will aim to have that done by Friday, but I would create the store on both sites to have a backup plan in case I run into any other major issues. It could be a good test run for the new site to have this set up on it, even if it doesn't end up being used live yet.
