### ISSUE TITLE
Rearrange product display order?

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#19]
Do we have the ability to rearrange the order in which products appear on a store?  Or do they appear in the order we create them?  Just thinking it could be helpful to put polo shirts near each other, for example, and maybe after setting up all products the client asks to add one more polo.  It would be nice if I could add the new polo and choose to have it appear near the other polos.

**Comment by smitdalt** [comment]
Added a display order field to products.
