### ISSUE TITLE
Access Code for Peshtigo National Bank

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#22]
I had previously set up a store for Peshtigo National Bank.  Today I went in and chose to Edit the store details.  During that edit process, I selected alternative payment method and then entered PNB2021 as the access code and saved.  Then I created 3 new products in the store and started testing it out as if I was a shopper.  I put one sport shirt in my cart and when I tried to check out, it asked me for the access code.  I put in PNB2021 but am getting an error message that says "incorrect access code provided".

**Comment by smitdalt** [comment]
Fixed

**Comment by smitdalt** [comment]
I also set the access code to PNB2021 for you
