### ISSUE TITLE
Product color issue

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#23]
In the Peshtigo store, I added a Ladies Nike Pullover in white.  When I get to the screen where I add the product color, it will not accept it when I want to choose white as the color.  So the color hex code would stay as the default ffffff but it won't seem to save it no matter what I try.  Also, in the process of trying, I selected to add another color.  But I really don't want a second color and now I have no way of removing that 2nd color option.  I think I can only delete the product completely and create it again as a new product?

**Comment by smitdalt** [comment]
This is a limitation of the color picker library I used. If you want to create a White I would just use fffffe as the hex code, no one will be able to see a difference
