### ISSUE TITLE
Multiple images for one product

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#25]
I know you said we already have the ability to upload multiple images for one product but I am not seeing where/how to do that.  There is a spot to upload the Default Product Image in the first step but I don't see where to add more images.  

Also, when adding a garment color, I see there is a spot there to upload an image.  What is that intended for?  Out of curiousity, I added a different product image there to see where/how it would be displayed but I don't see it anywhere when I go back to shop the store.  So I don't see what this is for. ??

Thank you!
Karen

**Comment by smitdalt** [comment]
The default product image is used if there are no color images uploaded. You can add different pictures for each color, so if you had the same product in multiple colors you can upload pictures with the different colors. For each color is where you can upload multiple images at the same time.

When you upload multiple images for a color then you can click through them on the product page. If you click on a different color or select a different color when looking at a product then the images for that color will be shown.

**Comment by karentooley** [comment]
Okay, so is it possible to have multiple product images for just one color?  For example, say my product is the Ladies Nike Stretch Pullover and we are only offering it in White.  But I want to show the front of the garment (default) AND I want to show the back of the garment because maybe it has an unusual back or people want to see how it lays in the back.  Or maybe we add a product that has a logo on the front and a logo on the back so in that case we'd want to show the front of the garment and the back of the garment so the buyer can see both logos.  Is this possible??

**Comment by smitdalt** [comment]
Yes, just upload both/all the images under the one color instead of the default product image. Color images override the default product image when they exist

**Comment by karentooley** [comment]
Okay, so for the Ladies royal blue sport shirt...when I got to the add color page I uploaded a front image and a back image to this garment using the same "choose files" link by the one color.  Now when I'm on the home page of their store as if I'm shopping, I see the front of the ladies shirt as the default image which is good.  When I click on that shirt, now what I see first is the back of the shirt which seems weird.  I can click the arrow over to see the next image which is the front of the shirt.  Is there a way to make the front of the shirt appear first?  Or is it dependant upon the order in which I upload the images?

**Comment by smitdalt** [comment]
It is dependent on the order uploaded. I can invert the order they are returned so the first image uploaded is the first displayed if that makes more sense.

**Comment by karentooley** [comment]
Ah, I see.  Um, if it is easy to do, then yes, I would say invert the order.  My thought-process is I would upload the image I want to appear first first, then subsequent images in order after that.  Thx!

**Comment by smitdalt** [comment]
Already done, If you hold shift and refresh the page it should be in the correct order

**Comment by karentooley** [comment]
awesome - thx
