### ISSUE TITLE
Update Blue Fuel logo on Landing Page

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#30]
I'm not sure what logo format is ideal for you but pasting a PDF link here of our new logo.  We can email you whatever version is needed if that would be better.  TY!

[Primary Logo_FC_NavyBG.pdf](https://github.com/smitdalt/BFStoreIssues/files/6273062/Primary.Logo_FC_NavyBG.pdf)

**Comment by smitdalt** [comment]
Is there a PNG version of the logo with a transparent background? I think that would be the best option as that is what I currently have with the old logo.

**Comment by smitdalt** [comment]
If so, you can email it to daltonsmith45@hotmail.com. Thanks!
