### ISSUE TITLE
Store access blocked?

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#31]
When I first shared the stores.bluefuelmarketing.com url with Peshtigo National Bank, they could see our landing page except could not see the Peshtigo National Bank link, like there was nothing there.  I'm not really sure what he did on his end but he mentioned talking to his IT dept and then he got it to work so my impression was their system was blocking it.

Today I shared the same link with Shopko Optical bc they are interested in doing a simple store, too, and I wanted to show them what Peshtigo's looked like.  But when she tried the link, she also can only see the landing page and not the Peshtigo Store link.

So this has me wondering if this is going to be a problem.  Are there instructions I should give clients to be able to view the link?  Like maybe some security things they need to change on their end?  I was intending to create a spirit wear store for my kids' school which would then be an assortment of parents all over who would be placing orders - not like employees at one company using the same server/security.  So are all of these parents going to have a hard time seeing the store links??

Thoughts?

**Comment by smitdalt** [comment]
This site works no differently than almost every modern interactive site. There shouldn't be any security changes needed to see the stores. 

Are you sure they are waiting long enough for the stores to load? When the API hasn't been used in a while it shuts down to save resources and resumes when a new request is made, which could take up to 10 seconds after a new request. After that it will function normally without significant loading times. I would just make sure everyone knows to wait for the site to fully load the first time they access it in a time period.
