### ISSUE TITLE
Shopko store - add to cart kicks us back to Blue Fuel home page

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#33]
According to my client with Shopko, when she selects ADD TO CART after picking a product, it brings her back to the Blue Fuel landing page where she has to click on the Shopko store again.  It's odd because it does not do that for me??  But that is apparently what is happening to her.  Any idea??

**Comment by smithdalt** [comment]
ADD TO CART should take you to the checkout page, while ADD TO CART AND CONTINUE will take you back to the store page. I'm not exactly sure which one she is pressing and what outcome she expects. If you hit ADD TO CART AND CONTINUE then you can click on the shopping cart icon to see what's in the cart and continue to checkout from there.

**Comment by smithdalt** [comment]
Would it make more sense for one to say ADD TO CART and the other CHECKOUT NOW? I guess the labels aren't very user friendly

**Comment by karentooley** [comment]
I specified exactly that to her and that is exactly how it works for me, no problem.  But then she replied when she clicks the Add to Cart button, that she is brought back to the Blue Fuel home page and has to click Shopko Optical again.  I don't get why it would be working differently for her...?

**Comment by smithdalt** [comment]
That definitely shouldn't be the case.. Do you know which product it is?

**Comment by karentooley** [comment]
I think ADD TO CART & CONTINUE, verses ADD TO CART are perfectly understandable.  I don't think that needs to be changed.

**Comment by smithdalt** [comment]
I can't replicate this. On the checkout page if you hit CANCEL it will take you back to the home page, but otherwise ADD TO CART took me to checkout without fail

**Comment by karentooley** [comment]
Same for me.  Sigh...truthfully this customer is one of those people who are always unhappy about everything. She just replied to me that she put 1 MD of the Nike Vertical Mesh in her cart but was then brought to landing page.  I just tried that and could not replicate her issue either - it is working perfectly fine for me!  I'll ask if there's any way she is accidentally clicking the Cancel button.  She is always difficult - sorry!

**Comment by karentooley** [comment]
Her response to my Q about accidentally hitting cancel..."NOT POSSIBLE".  lol!  Oh, she's a peach.  I just asked her to try it from her phone, out of curiosity, to see if she still has the same issue.

**Comment by smithdalt** [comment]
I checked the logs to see if there are any errors just to be sure.. I've got nothing

**Comment by karentooley** [comment]
This is her response to me, "Well that was even stranger. All that showed up after size was the word quantity but nothing to click on, no add to cart buttons or anything. I hit the screen multiple times and finally got the add to cart etc buttons to display. Then when I added to cart it took me to the cart."   Could something be wonky with her web browsing security or something like that, like blocking certain things??  I don't know, I'm stretching here...

**Comment by karentooley** [comment]
I wonder is she is just not being patient enough to let things load.  She is the same person who claimed it was 10+ minutes before the Peshtigo store would load for her.

**Comment by karentooley** [comment]
Though that doesn't explain why she's getting kicked back to the landing page.

**Comment by karentooley** [comment]
She just emailed me a little i-movie she made so that we don't think she's crazy.  It is a video showing her clicking the button ADD TO CART and it legit brought her back to the main landing page!  I'm baffled.

**Comment by smithdalt** [comment]
If it was something related to browser security she probably wouldn't be able to see the site at all, and it wouldn't redirect her to the home page then anyways.

I'm not at my computer at the moment but I'll see if there is some weird case that redirects back to the home page for any reason when I get back.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by smithdalt** [comment]
Can you send me the video she took? I can't see any reason that this would be happening

**Comment by karentooley** [comment]
https://user-images.githubusercontent.com/78398601/117192283-23669080-ada7-11eb-91a2-bb45c768a13f.MOV

**Comment by smithdalt** [comment]
The error in the bottom says why.. I forgot about that. I only allow shopping in one store at a time, because it simplifies things and almost no one will be buying things from both Shopko and PNB... etc. She has an item from PNB store in the cart so it won't allow her to add one from Shopko too. She just needs to go into the cart and remove the item from PNB.

**Comment by karentooley** [comment]
Oooo, that makes perfect sense!!  Yes, no one would ever have items from multiple stores in their cart normally.  She was just trying things out in the peshtigo store before we created the shopko store and I never thought about something still being in her cart.  I just emailed her that info so I suspect that will solve it - TY!!
