### ISSUE TITLE
Credit Card Error

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#34]
When I click "Debit or Credit Card" for the payment to check out, I am receiving an error message.  I'll drag in a screen shot.  

![cc error](https://user-images.githubusercontent.com/78398601/117349505-101ff780-ae71-11eb-85cf-264727502820.JPG)

**Comment by smithdalt** [comment]
I will fix this. One of the description fields is too long for PayPal so I will either truncate the value or use another field.

**Comment by smitdalt** [comment]
Fixed
