### ISSUE TITLE
Delete an item from cart?

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#36]
If I click the cart icon in the upper right and am brought to that shopping cart, I see the trash cans where I can delete any items I may want to.  But if I'm buying an item and click the ADD TO CART button, that particular cart I am brought to (which looks different b/c this version includes product images), in that cart I do not have a way to delete anything.  And then my next steps would be to enter ship to and payment info.  I don't know that people would naturally think they have to click that cart icon to see the cart that particular way to be able to delete anything.  ?

![image](https://user-images.githubusercontent.com/78398601/117497790-8b031400-af3e-11eb-8ded-e83cf4b1ac99.png)

**Comment by smitdalt** [comment]
That's the checkout overview page, not the cart. I could still add a way to delete from there if that would make sense.

**Comment by karentooley** [comment]
I think we have to.  Because from this screen, I click Continue to Checkout and I'm brought to the ship to page.  Then the credit card page and then I'm done.  If I was staring at this page and wanted to delete something from my cart, I think I might be looking around awhile thinking how do I get something out of my cart.  I don't think it is obvious to go to the cart icon since I can technically checkout right from here.

**Comment by smitdalt** [comment]
Added deletion on overview page.
