### ISSUE TITLE
Shopko - credit card processing?

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#38]
Shopko wants to open their store on Monday.  I added a test item that only cost $.01 and tried to purchase it to test and make sure the credit card processing is working.  When I click the Debit or Credit Card button in check out, I received an error message.   "Something went wrong.  Please try again later."  Can you help??

**Comment by smitdalt** [comment]
Go ahead and try again. I had to update another field

**Comment by karentooley** [comment]
It works!!  Thank you!!!!  Now go enjoy graduation and congratulations!!!
