### ISSUE TITLE
reports

### ISSUE THREAD

**Issue by karentooley** [smitdalt/BFStoreIssues#39]
This are the reports I got from the Shopko and Peshtigo stores.  I don't know what is happening but I have no way of knowing what items each person ordered.  Shopko is more urgent as that store closed today so I have to get those items ordered asap.  Peshtigo store is open a while longer.

**Comment by smitdalt** [comment]
Can you email them to me? (Daltonsmith45@hotmail.com) Not sure if you tried to attach them but I don't see any files here.

**Comment by karentooley** [comment]
Any further thoughts on this?  Did the order confirmation emails go somewhere that I can retrieve them?  Even if I could see on each email what each person ordered I could manually tabulate the items.

**Comment by smitdalt** [comment]
Okay - this was a bit of an "interesting" issue (in that I really don't know **why** it was occurring, but I do know **where**), but it should be fixed now. If you download new reports then all the ordered items should be filled into the CSV file.
