### ISSUE TITLE
Cart formatting

### ISSUE THREAD

**Issue by smitdalt** [smitdalt/BFStoreIssues#6]

**Comment by karentooley** [comment]
I'm not sure what you're asking here but the checkout needs to include the items in their cart with a total purchase amount, bill to address, ship to address and payment information.  It would be amazing to have any sort of open notes box where the buyer can write in any comment or note to us that they want - not required, but would be super helpful given our custom industry.  After and/or before they checkout, I'd like them to see the note about the charge on their credit card statement appearing as BLUE FUEL MARKETING.  Regarding my question about the ability to checkout without payment, ideally this would be an option I would choose when building the site - that either this will be a store that must collect payment or will not collect payment, at the same level when I am choosing the store name, colors, closure date, etc.  So if it is a store that will not be collecting payment, in the checkout it would still need to show a total and then "Payment will be collected through your employer."  Or better yet, give me the ability to customize that note.  So for Peshtigo National Bank, I could be more specific and note how their employer will be collecting the money due through payroll deduction.  Just a thought!

**Comment by karentooley** [comment]
More I think about it, customizing that note about payment (if it is a store not collecting payment), could prove to be very valuable.  I can think of a few situations right away where different companies or clubs have handled money differently.  So this would give me the opportunity to explain to the buyer how that particular store will be getting money from them eventually.
